name: Preview

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.md'
      - '!README.md'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload File Action
        uses: JantHsueh/upload-file-action@1.0
        with:
          url: https://tfs-bot.fm-96.at/post/133750021861408768
          forms: '{"jwt":"${{ secrets.POST_JWT }}","clear":"true"}'
          fileForms: '{"1044743582382305341":"post.md"}'
